---
- src: https://github.com/mrlesmithjr/ansible-etc-hosts.git

# Forked version of: src: https://github.com/mrlesmithjr/ansible-rabbitmq.git
- src: https://github.com/makingspace/ansible-rabbitmq.git


